---
title: "gsea_analysis"
format: html
---

# Set up

## Packages

These packages are used in the analysis:

```{r Loading packages, warning=FALSE}
# Loading packages
library(tidyverse) # v.2.0.0
library(embed) # v.1.1.3
library(umap) # v0.2.10.0
library(ggrepel) # v.0.9.4
library(readxl) # v.1.4.3
library(openxlsx) # v.4.2.7
library(HDAnalyzeR) # v.1.0.0
library(ggridges) # v.0.5.6
library(patchwork) # v.1.3.0
library(ComplexUpset) # v.1.3.3
library(doParallel) # v.1.0.17
library(viridis) # v.0.6.5
library(fmsb) # v.0.7.6
library(RColorBrewer) # v.1.1-3
library(org.Hs.eg.db) # v.3.21.0
```

```{r}
select <- dplyr::select
filter <- dplyr::filter
mutate <- dplyr::mutate
arrange <- dplyr::arrange
rename <- dplyr::rename
```

## Read data

```{r}
de_results_aml <- read_excel("../tables/DA_proteins_AML_vs_controls.xlsx")
head(de_results_aml)
```

# Figure 3S: GSEA analysis

```{r}
# Code to fix the Entrez to Symbol conversion in the enrichment plots

# Create a mapping function for a single string
convert_ids <- function(id_string) {
  # Split the string into individual IDs
  ids <- unlist(strsplit(id_string, "/"))
  
  # Map Entrez IDs to Symbols
  symbols <- mapIds(org.Hs.eg.db, 
                    keys = ids, 
                    column = "SYMBOL", 
                    keytype = "ENTREZID", 
                    multiVals = "first")
  
  # Replace any NAs with the original ID (optional) and paste back with "/"
  symbols[is.na(symbols)] <- ids[is.na(symbols)]
  return(paste(symbols, collapse = "/"))
}
```

## AML vs. Healthy

```{r}
de_aml_healthy <- de_results_aml |> 
  dplyr::select(Feature, logFC = logFC_healthy, adj.P.Val = adj.P.Val_healthy, sig = sig_healthy)
```

```{r}
set.seed(1234)

enrichment <- hd_gsea(de_aml_healthy, 
                      database = "GO", 
                      ontology = "BP",
                      ranked_by = "logFC",
                      pval_lim = 0.05)

enrichment_plots <- hd_plot_gsea(enrichment)

enrichment_plots$dotplot

enrichment_plots$dotplot$data

enrichment_data_aml_healthy <- enrichment_plots$dotplot$data %>%
  mutate(core_enrichment = sapply(core_enrichment, convert_ids))
```

## AML vs. Pan-cancer

```{r}
de_aml_pan_cancer <- de_results_aml |> 
  dplyr::select(Feature, logFC = logFC_cancer, adj.P.Val = adj.P.Val_cancer, sig = sig_cancer)
```

```{r}
set.seed(1234)

enrichment <- hd_gsea(de_aml_pan_cancer, 
                      database = "GO", 
                      ontology = "BP",
                      ranked_by = "logFC",
                      pval_lim = 0.05)

enrichment_plots <- hd_plot_gsea(enrichment)

enrichment_plots$dotplot

enrichment_data_aml_pan_cancer <- enrichment_plots$dotplot$data %>%
  mutate(core_enrichment = sapply(core_enrichment, convert_ids))
```

## AML vs. Hematological malignancies

```{r}
de_aml_hm <- de_results_aml |> 
  dplyr::select(Feature, logFC = logFC_hm, adj.P.Val = adj.P.Val_hm, sig = sig_hm)
```

```{r}
set.seed(1234)

enrichment <- hd_gsea(de_aml_hm, 
                      database = "GO", 
                      ontology = "BP",
                      ranked_by = "logFC",
                      pval_lim = 0.05)

enrichment_plots <- hd_plot_gsea(enrichment)

enrichment_plots$dotplot

enrichment_data_aml_hm <- enrichment_plots$dotplot$data %>%
  mutate(core_enrichment = sapply(core_enrichment, convert_ids))
```

## AML vs. CLL

```{r}
de_aml_cll <- de_results_aml |> 
  dplyr::select(Feature, logFC = logFC_cll, adj.P.Val = adj.P.Val_cll, sig = sig_cll)
```

```{r}
set.seed(1234)

enrichment <- hd_gsea(de_aml_cll, 
                      database = "GO", 
                      ontology = "BP",
                      ranked_by = "logFC",
                      pval_lim = 0.05)

enrichment_plots <- hd_plot_gsea(enrichment)

enrichment_plots$dotplot

enrichment_data_aml_cll <- enrichment_plots$dotplot$data %>%
  mutate(core_enrichment = sapply(core_enrichment, convert_ids))
```

## AML vs. Lymphoma

```{r}
de_aml_dbcl <- de_results_aml |> 
  dplyr::select(Feature, logFC = logFC_lymphoma, adj.P.Val = adj.P.Val_lymphoma, sig = sig_lymphoma)
```

```{r}
set.seed(1234)

enrichment <- hd_gsea(de_aml_dbcl, 
                      database = "GO", 
                      ontology = "BP",
                      ranked_by = "logFC",
                      pval_lim = 0.05)

enrichment_plots <- hd_plot_gsea(enrichment)

enrichment_plots$dotplot

enrichment_data_aml_dlbcl <- enrichment_plots$dotplot$data %>%
  mutate(core_enrichment = sapply(core_enrichment, convert_ids))
```

## AML vs. Myeloma

```{r}
de_aml_myeloma <- de_results_aml |> 
  dplyr::select(Feature, logFC = logFC_myeloma, adj.P.Val = adj.P.Val_myeloma, sig = sig_myeloma)
```

```{r}
set.seed(1234)

enrichment <- hd_gsea(de_aml_myeloma, 
                      database = "GO", 
                      ontology = "BP",
                      ranked_by = "logFC",
                      pval_lim = 0.05)

enrichment_plots <- hd_plot_gsea(enrichment)

enrichment_plots$dotplot

enrichment_data_aml_myeloma <- enrichment_plots$dotplot$data %>%
  mutate(core_enrichment = sapply(core_enrichment, convert_ids))
```

# Write to tables

```{r}
enrichment_res <- bind_rows(
  aml_healthy = enrichment_data_aml_healthy,
  aml_pan_cancer = enrichment_data_aml_pan_cancer,
  aml_hm = enrichment_data_aml_hm,
#  aml_cll = enrichment_data_aml_cll, # no significant terms were found
  aml_dlbcl = enrichment_data_aml_dlbcl,
  aml_myeloma = enrichment_data_aml_myeloma,
  .id = "comparison"
)

enrichment_res |> write.xlsx("../tables/enrichment_results.xlsx", overwrite = TRUE)
```

# Summarize

```{r}
library(dplyr)

top_terms_union <- enrichment_res %>%
  group_by(comparison) %>%
  arrange(p.adjust, .by_group = TRUE) %>%
  slice_head(n = 10) %>%
  ungroup() %>%
  distinct(Description)
  

plot_df <- enrichment_res %>%
  filter(Description %in% top_terms_union$Description) |>
  mutate(
    comparison = recode(comparison,
      "aml_healthy" = "Healthy",
      "aml_pan_cancer" = "Pan-cancer",
      "aml_hm" = "Hematological malignancies",
      "aml_cll" = "CLL",
      "aml_dlbcl" = "DLBCL",
      "aml_myeloma" = "Myeloma"
    )
  )

plot_df <- plot_df %>%
  mutate(
    logP = -log10(p.adjust),
    NES_abs = abs(NES)
  )

term_order <- plot_df %>%
  group_by(Description) %>%
  summarise(min_p = min(p.adjust, na.rm = TRUE)) %>%
  arrange(min_p) %>%
  pull(Description)

plot_df$Description <- factor(plot_df$Description,
                              levels = rev(term_order))

plot_df$comparison <- factor(
  plot_df$comparison,
  levels = c(
    "Healthy",
    "Pan-cancer",
    "Hematological malignancies",
    "CLL",
    "DLBCL",
    "Myeloma"
  )
)

library(ggplot2)

ggplot(plot_df, aes(x = comparison, y = Description)) +
  geom_point(aes(size = NES_abs, color = logP)) +
  scale_color_viridis_c(option = "plasma") +
  scale_size_continuous(range = c(3, 10)) +
  labs(
    x = NULL,
    y = NULL,
    color = expression(-log[10](adj.~p)),
    size = "NES"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid.major = element_line(color = "grey90"),
    panel.grid.minor = element_blank()
  )

ggsave("../plots/png/dotplot/enrichment_plot.png", width = 8, height = 10, dpi = 300)
ggsave("../plots/pdf/dotplot/enrichment_plot.pdf", width = 8, height = 10)
```

```{r}
library(dplyr)
library(tidyr)
library(stringr)

network_df <- enrichment_res |>
  mutate(
    comparison = recode(comparison,
      "aml_healthy" = "Healthy",
      "aml_pan_cancer" = "Pan-cancer",
      "aml_hm" = "Hematological malignancies",
      "aml_cll" = "CLL",
      "aml_dlbcl" = "DLBCL",
      "aml_myeloma" = "Myeloma"
    )
  ) |>
  filter(Description == "homeostasis of number of cells") |>
  select(comparison, core_enrichment) |>
  mutate(core_enrichment = str_split(core_enrichment, "/")) |>
  unnest(core_enrichment) |>
  rename(protein = core_enrichment) |>
  distinct()

nodes <- data.frame(
  name = unique(c(network_df$comparison, network_df$protein))
) |>
  mutate(
    type = ifelse(name %in% network_df$comparison,
                  "Comparison",
                  "Protein")
  )

edges <- network_df |>
  rename(from = comparison,
         to = protein)

library(igraph)

graph <- graph_from_data_frame(edges, vertices = nodes)
V(graph)$degree <- degree(graph)

V(graph)$plot_size <- ifelse(
  V(graph)$type == "Protein",
  V(graph)$degree,   # number of comparisons
  8                  # fixed size for comparisons
)

library(ggraph)
library(ggplot2)

ggraph(graph, layout = "fr") +
  geom_edge_link(alpha = 0.3) +
  geom_node_point(aes(color = type, size = plot_size)) +
  geom_node_text(aes(label = name),
                 repel = TRUE,
                 size = 3) +
  scale_color_manual(values = c(
    "Comparison" = "#D55E00",
    "Protein" = "#0072B2"
  )) +
  scale_size_continuous(range = c(3, 10)) +
  theme_void() +
  theme(legend.position = "top")

ggsave("../plots/png/network/enrichment_network.png", width = 8, height = 6, dpi = 300)
ggsave("../plots/pdf/network/enrichment_network.pdf", width = 8, height = 6)
```

# SessionInfo

```{r}
sessionInfo()
```

End of file.
