---
title: "Blood plasma profiling using proximity extension assay in patients with acute myeloid leukemia"
subtitle: "Enrichment analyses"
author: "Emil Johansson, María Bueno Álvez, Sören Lehmann, Tobias Sjöblom, Ulf Gyllensten, Fredrik Pontén, Göran Bergström, Adil Mardinouglu, Wen Zhong, Mathias Uhlén & Fredrik Edfors"
date: last-modified
date-format: "dddd [the] Do [of] MMMM YYYY"
format:
  html:
    theme: lumen
    title-block-banner: true
    smooth-scroll: true
    toc: true
    toc-depth: 4
    toc-location: right
    number-sections: true
    number-depth: 4
    code-fold: true
    code-tools: true
    code-copy: true
    code-overflow: wrap
    df-print: kable
    standalone: true
    fig-align: left
    figure:
      caption: "Figure {number}: {label}"
editor_options: 
  chunk_output_type: inline
execute:
  echo: true
  message: false
  warning: false
params: 
  disease: "Abdominal aortic aneruysm"
editor: 
  markdown: 
    wrap: 72
---

Start of document.

# Background

## Introduction

Welcome to the quarto report presenting the code used to generate the content to the article: "Blood proteome profiling using proximity extension assay in patients with acute myeloid leukemia" by Emil Johansson, María Bueno Álvez, Sören Lehmann, Tobias Sjöblom, Ulf Gyllensten, Fredrik Pontén, Göran Bergström, Adil Mardinouglu, Wen Zhong, Mathias Uhlén & Fredrik Edfors..

## The study

The results from the study are published in **insert journal**: Johansson, E, et al. Blood proteome profiling using proximity extension assay in patients with acute myeloid leukemia. Insert journal here\* (2024). **insert DOI here**

## Access the data/scripts

The results generated by this study can be accessed through the Human Protein Atlas (HPA) (<https://www.proteinatlas.org/>). More specifically, the data is presented in the disease section of the HPA (<https://www.proteinatlas.org/humanproteome/disease>).

Scripts used to create the figures here can be found here: <https://github.com/eemiljohansson/AML-profiling>.

# Set up

## Packages

These packages are used in the analysis:

```{r Loading packages, warning=FALSE}
# Loading packages
library(tidyverse) # v.2.0.0
library(embed) # v.1.1.3
library(umap) # v0.2.10.0
library(ggrepel) # v.0.9.4
library(readxl) # v.1.4.3
library(openxlsx) # v.4.2.7
library(HDAnalyzeR) # v.1.0.0
library(ggridges) # v.0.5.6
library(patchwork) # v.1.3.0
library(ComplexUpset) # v.1.3.3
library(doParallel) # v.1.0.17
library(viridis) # v.0.6.5
library(fmsb) # v.0.7.6
library(RColorBrewer) # v.1.1-3
```